<?php
return [
    "hasiera" => "Inicio",
    "guri_buruz" => "Sobre nosotros",
    "habitatak" => "Habitats",
    "ekitaldiak" => "Eventos",
    "login" => "Iniciar sesion",
    "aldatu" => "Cambiar",
    "ongietorri" => "Bienvenido al zoologico BBC",
    "ordutegi" => "Horarios de apertura:",
    "ordutegi1" => "Lunes a Viernes: 9:00 AM - 6:00 PM",
    "ordutegi2" => "Sabados y Domingos: 9:00 AM - 7:00 PM",
    "ordutegi3" => "Festivos: 10:00 AM - 5:00 PM",
    "prezioak" => "Precios:",
    "helduak" => "Adultos(12+ años): 15€",
    "umeak" => "Niños/Niñas (3-12 años): 10€",
    "haurrak" => "Bebes (0-3 años): 0€",
    "taldeak" => "Grupos(10+): Descuento del %20",
    "arauak" => "Reglas para visitantes:",
    "arau1" => "Respeta los horarios de cierre del zoologico",
    "arau2" => "No alimentar a los animales",
    "arau3" => "Mantener una distacia segura con respecto a los recintos de los animales",
    "arau4" => "Prohibido tocar cristales y rejas",
    "arau5" => "Los menores deben ir acompañados por un adulto",
    "arau6" => "Prohibido traer comida de fuera del zoologico",
    "arau7" => "Prohibido consumir bebidas alcoholicas",
    "arau8" => "Respeta la señalizacion del zoologico",
    "zerbitzuak" => "Servicios:",
    "zerb1" => "Restaurante y Cafeteria",
    "zerb2" => "Tienda de souvenirs",
    "zerb3" => "Zona de descanso",
    "zerb4" => "Baños publicos",
    "zerb5" => "Parking gratuito"
];